microsoft/adaptivecards-templates

.github/CODEOWNERS

We will use this file to require a coach, sponsor or garage LT to review along with at least one intern each PR

Add CODEOWNERS for PR review

---

private-templates-service/adaptivecards-templating-service/src/models/models.ts
private-templates-service/adaptivecards-templating-service/src/models/mongo/TemplateModel.ts
private-templates-service/adaptivecards-templating-service/src/models/mongo/UserModel.ts
private-templates-service/adaptivecards-templating-service/src/storageproviders/InMemoryDBProvider.ts

Update MongoSchema to work with updated by Grace data models:
1) **IUser**: **authId and issuer fields** were added. **Email field** was removed
2) **Tags** field for ITemplate is now optional.
I have also modified **matchTemplate** function of **InMemoryStorageProvider** to correctly query based on the data models changes.

Fix mongo schema to work with update models

---

private-templates-service/client/src/App.tsx
private-templates-service/client/src/Services/GraphService.ts
private-templates-service/client/src/components/SideBar/SideBar.tsx
private-templates-service/client/src/components/SideBar/UserAvatar.tsx
private-templates-service/client/src/components/SideBar/styled.tsx
private-templates-service/client/src/store/auth/actions.ts
private-templates-service/client/src/store/auth/reducers.ts
private-templates-service/client/src/store/auth/types.ts

This pr adds profile pictures associated with microsoft account. It also moves the other api calls to microsoft graph into redux, and saves the access token into the store.
[AB#33705](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/33705)
No profile picture:
Profile picture:

Display Profile Picture + Move Microsoft Graph into Redux

---

private-templates-service/client/src/Config.tsx

[AB#33794](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/33794)
Separate app-registration IDs should fix the bug where users cannot log in because they are already logged-in in another url.

Add additional appID

---

private-templates-service/adaptivecards-templating-service/src/TemplateServiceClient.ts
private-templates-service/adaptivecards-templating-service/src/models/models.ts
private-templates-service/adaptivecards-templating-service/src/models/mongo/TemplateModel.ts
private-templates-service/adaptivecards-templating-service/src/storageproviders/MongoDBProvider.ts
private-templates-service/adaptivecards-templating-service/src/tests/router.test.ts
private-templates-service/adaptivecards-templating-service/src/tests_helper/db_t_definition.ts
private-templates-service/adaptivecards-templating-service/src/util/mongoutils/mongoutils.ts
private-templates-service/adaptivecards-templating-service/src/util/templateutils.ts

[ACB-33792](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/33792)
In this PR I've addressed an issue of saving template JSON as string to db while retrieving it as JSON. The reason for not storing template as JSON in db is due to Mongo Limitation of not allowing **$** and **.** in key names.
What has been done to solve it:
1) **TemplateInstanceModel** was updated to have **json** and **data** in JSON format
2) Before saving it to db, both json and data fields will be converted to String
3) When retrieving templates from the db, json and data fields will be converted back to JSON format
In the postman when retrieving the template:

Fix json encoding

---

.github/workflows/azure-stage.yml

Stage deployment did not work because we used the word "stage" instead of "staging".

Change run build:stage to run build:staging

---

private-templates-service/client/src/Services/ProcessTemplate.ts
private-templates-service/client/src/components/AdaptiveCardPanel/styled.tsx
private-templates-service/client/src/components/Common/PublishModal/PublishModal.tsx
private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/TemplateInfo.tsx
private-templates-service/client/src/components/Gallery/styled.tsx

This short PR fixes three things:
1. Previously, publish was not working because the definition of template.json changed from a string to a JSON object. The fix was to stringify before passing into the function
2. Date timestamp was previously ISO time, its now parsed to a more human readable time
3. Cards are formatted to have some additional spacing, minor change.

Fix Publish, Timestamp, and Card Formatting

---

private-templates-service/adaptivecards-templating-service/src/TemplateServiceClient.ts
private-templates-service/adaptivecards-templating-service/src/util/templateutils.ts

`GET /template/{id}` now returns all template versions sorted by most recent.

Update backend to return template versions sorted by most recent version

---

private-templates-service/client/src/components/Dashboard/SearchPage/SearchPage.tsx

Adding quick fix for a search page bug.
The bug:
templates on the search page were not being properly rendered when clicked and would only show the previously rendered card that was clicked on the dashboard. 
The Solution:
This bug was caused since the seachpage did not properly call the getTemplate action.

 fixing search bug

---

private-templates-service/client/src/components/Dashboard/PreviewModal/PreviewModal.tsx
private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/TemplateInfo.tsx

Fixed bug in "Template Info" page. 
Before: It always displayed version 1.0 of the template, even though the dashboard displays the most recent version of the template.
After: It defaults to displaying the most recent version of the template in the "Template Info" page.

Fix version bug in TemplateInfo.tsx

---

private-templates-service/client/src/App.tsx
private-templates-service/client/src/components/Common/PublishModal/PublishModal.tsx
private-templates-service/client/src/utils/ModalHOC.tsx

[AB#33910](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/33910)
Previously, users can interact with the navbar even when a modal is open. This is because the modal is previously a child of a dashboard component. No matter how high the z-index is set, it will never be positioned higher than the navbar, which only shares a common ancestor node. 
The modal must be positioned higher up in the DOM so the navbar and the modal are direct decedents of each other. This was done easily with [React Portals](https://reactjs.org/docs/portals.html). From now on, all modals should use the ModalHOC component.

Create modal HOC to position modal closer to app root

---

private-templates-service/adaptivecards-templating-client/swagger.yaml
private-templates-service/adaptivecards-templating-client/typescript/api.ts
private-templates-service/adaptivecards-templating-service/src/TemplateServiceClient.ts
private-templates-service/adaptivecards-templating-service/src/models/mongo/TemplateModel.ts
private-templates-service/client/src/store/currentTemplate/actions.ts
private-templates-service/client/src/store/search/actions.ts
private-templates-service/client/src/store/templates/actions.ts

This PR makes sure the client accessing template by id does not increase the number of hits on the template. 
**Changes**
- Fix mongo provider bug using hits instead of numHits field 
- Add client query param flag to client SDK definition + update client
- Fix client SDK data type to any (for JSON object) instead of string

Update client to use client flag to track template hits

---

private-templates-service/adaptivecards-templating-service/src/TemplateServiceClient.ts

This PR removes an unused isClient check in the backend code that causes the backend to return an error.

Fix client flag bug in backend 

---

private-templates-service/client/src/components/Dashboard/PreviewModal/styled.tsx

[AB#33964](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/33964)
For unknown reasons, a small number of templates do not render properly on the template preview page. This one liner fixes that.

Fix render bug

---

private-templates-service/server/src/app.ts

[AB#33908](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/33908)
Previously, URLs like `/preview` and `/designer` would not load. This is because we were not serving the frontend for all URLs, only the root URL `/`.
This change allows the frontend to be served so long as no other endpoints have other definitions. This means our rest endpoints will have priority over the frontend, which is the expected behavior.

Allow non REST-endpoint URLS to be handled by the client

---

private-templates-service/adaptivecards-templating-service/src/TemplateServiceClient.ts
private-templates-service/adaptivecards-templating-service/src/tests/router.test.ts

[BUG-34047](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_backlogs/backlog/Adaptive%20Cards/Backlog%20items/?workitem=34047)
This PR adds authentication check to all endpoints under /template to fix the bug where only one user persists on the dev website (the last user to edit the templates shows up on the dashboard under recent templates).
The backend will be refactored to allow multiple users to use the same client (or a wrapper around the client) after discussion with coaches and rest of team.

Quick fix for user bug in dev

---

.github/workflows/azure-dev.yml
.github/workflows/azure-stage.yml

Currently the stage and dev websites are both linked to the stagingDB. 
This PR will change the dev website to point to the `test` DB. The stage website will remain pointing to the `stagingDB`.

Separate stage and dev DBs

---

private-templates-service/adaptivecards-templating-service/src/TemplateServiceClient.ts
private-templates-service/adaptivecards-templating-service/src/authproviders/AzureADProvider.ts
private-templates-service/adaptivecards-templating-service/src/authproviders/IAuthenticationProvider.ts
private-templates-service/adaptivecards-templating-service/src/models/models.ts
private-templates-service/adaptivecards-templating-service/src/tests/router.test.ts
private-templates-service/adaptivecards-templating-service/src/util/templateutils.ts

**Background**
The backend uses the access token passed from the client to identify which user is trying to access their templates/info. The server instantiates one instance of the TemplateServiceClient, which connects to the auth and storage provider, which serves multiple users.
The backend also needs to be installed directly by an user using it as a npm package and so needs to support passing in the access token once instead of every time a function is used. 
**Issue**
Previously user information was stored as a class variable in TemplateServiceClient which sometimes caused the wrong user's templates or info to be returned to the client because of callbacks in the backend.
**Changes**
This PR updates each public function in TemplateServiceClient to take an access token. This ensures …

Multiple user bug fix

---

private-templates-service/adaptivecards-templating-service/src/storageproviders/InMemoryDBProvider.ts
private-templates-service/adaptivecards-templating-service/src/tests_helper/db_t_definition.ts
private-templates-service/client/package-lock.json
private-templates-service/client/package.json
private-templates-service/client/src/App.tsx
private-templates-service/client/src/globalConstants.ts

This pr addresses [ACB34148](git push --set-upstream origin users/vsevolod/34148-log-out) about logging the user out after 30 minutes of idle time.
It also fixes storage providers tests and InMemoryStorage providers based on models update in https://github.com/microsoft/adaptivecards-templates/pull/147
To test it locally with idle time less than 30 minutes:
Update `timeout` in `client/src/App.tsx`

Add automatic logout after 30 minutes of inactivity

---

private-templates-service/client/src/App.tsx

[AB#34066](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34066)
Sometimes an error will display on logging in, generated by microsoft active directory. This error no longer applies once the user is logged in, so we will not display it.

Don't Show Login Error once Authenticated

---

private-templates-service/client/src/components/Dashboard/RecentlyViewed/OwnerAvatar/OwnerAvatar.tsx
private-templates-service/client/src/components/Dashboard/RecentlyViewed/OwnerInfo/OwnerInfo.tsx
private-templates-service/client/src/components/Dashboard/RecentlyViewed/RecentlyViewedTable.tsx
private-templates-service/client/src/store/templateOwner/actions.ts
private-templates-service/client/src/store/templateOwner/types.ts

Problem:
Previously, the first template in the Recently Viewed Table showed `Error loading image`:
This is because we are using a dictionary where the keys were numbers to store the owner names/pics. The first key was always '0', but when we checked if '0' was a valid key, it evaluated to false.
Solution:
Although we could have switched the keys to start from '1', I changed the dictionary such that the key is the user's oID. This prevents duplicate values from being stored in the dictionary.

Fix 'Error loading image' in Recently Viewed Table

---

private-templates-service/adaptivecards-templating-service/src/authproviders/AzureADProvider.ts
private-templates-service/client/src/App.tsx
private-templates-service/client/src/store/auth/actions.ts
private-templates-service/client/src/store/auth/reducers.ts
private-templates-service/client/src/store/auth/types.ts
private-templates-service/client/src/store/currentTemplate/actions.ts
private-templates-service/client/src/store/recentTemplates/actions.ts
private-templates-service/client/src/store/search/actions.ts
private-templates-service/client/src/store/templates/actions.ts
private-templates-service/client/src/utils/TemplateUtil/TemplateUtil.ts
private-templates-service/client/src/utils/TemplateUtil/index.ts

**Ticket**: [TASK-34215](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_sprints/taskboard/Adaptive%20Cards/Intern%20GitHub/Y20-VW/10?workitem=34215)
**Issue**
Client was sending the id token that was only refreshed with the user logs in, this PR requests an access token for the registered web app whose audience is our web app rather than Microsoft Graph. This token is automatically refreshed by the AAD client that the frontend uses. The backend checks the expiry date, checks the audience is the web app id, and validates the token against the public certificate published by AAD. 
This PR contains changes from the previous reverted changes in this [PR](https://github.com/microsoft/adaptivecards-templates/pull/166).
**Azure App Registration Changes**
Each app registration now has …

Add app access token

---

private-templates-service/client/src/assets/strings.ts
private-templates-service/client/src/components/Dashboard/RecentlyViewed/OwnerAvatar/OwnerAvatar.tsx

[AB#34272](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_sprints/taskboard/Adaptive%20Cards/Intern%20GitHub/Y20-VW/10?workitem=34272) Add aria-label to Owner picture in recently viewed table

Add aria label

---

private-templates-service/client/src/components/AdaptiveCardPanel/AdaptiveCardPanel.tsx
private-templates-service/client/src/components/AdaptiveCardPanel/styled.tsx
private-templates-service/client/src/components/Dashboard/RecentlyViewed/RecentlyViewedTable.tsx
private-templates-service/client/src/globalKeyCodes.ts

[AB#34214](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34214)
Used Accessibility Insights Chrome Extension to identify and meet all keyboard navigation requirements.
Most of the site passed the requirements, few changes were needed:
- Making adaptive card panel accessible via keyboard (done by wrapping it in a styled `<button>`)
- Making the list view for "Recently viewed" keyboard accessible (done using `onKeyDown` and `tabIndex`)

Making app keyboard navigable

---

private-templates-service/adaptivecards-templating-service/src/TemplateServiceClient.ts

[TICKET-34069](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_sprints/taskboard/Adaptive%20Cards/Intern%20GitHub/Y20-VW/11?workitem=34069)
This PR reverse the order of the recently edited/viewed & tags results so that the most recent item is at the start of the array.

Flip order of recently edited/viewed & tags

---

private-templates-service/client/src/components/Common/Tags/Tags.tsx
private-templates-service/client/src/components/Common/Tags/styled.tsx
private-templates-service/client/src/components/Dashboard/PreviewModal/PreviewModal.tsx
private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/TemplateInfo.tsx
private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/VersionCard/VersionCard.tsx
private-templates-service/client/src/components/NavBar/NavBar.tsx
private-templates-service/client/src/components/SideBar/SideBar.tsx

[AB#34321](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34321)
[AB#34356](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34356)
This PR ensures that when a modal is open, buttons in the background are not keyboard accessible.
Also addressed making tagging feature keyboard accessible.

Keyboard Navigation on Modal View & Keyboard Navigation for Tags

---

private-templates-service/client/src/components/AdaptiveCardPanel/AdaptiveCardPanel.tsx
private-templates-service/client/src/components/AdaptiveCardPanel/styled.tsx
private-templates-service/client/src/components/Common/UnpublishModal/UnpublishModal.tsx

[AB#34320](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34320)
This PR reverts the implementation of AdaptiveCardPanel to a be contained by a div rather than a button to reduce UI complications.
The Unpublish Modal was also updated so that it used the AdaptiveCardPanel component rather than the AdaptiveCard component.

Fixing AdaptiveCardPanel UI on Unpublish Modal

---

private-templates-service/client/src/assets/strings.ts
private-templates-service/client/src/components/AdaptiveCardPanel/AdaptiveCardPanel.tsx
private-templates-service/client/src/components/AdaptiveCardPanel/styled.tsx
private-templates-service/client/src/components/Dashboard/Dashboard.tsx
private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/styled.tsx
private-templates-service/client/src/components/Dashboard/RecentlyViewed/OwnerAvatar/OwnerAvatar.tsx
private-templates-service/client/src/components/Dashboard/RecentlyViewed/OwnerAvatar/styled.tsx
private-templates-service/client/src/components/Dashboard/RecentlyViewed/OwnerInfo/OwnerInfo.tsx
private-templates-service/client/src/components/Dashboard/RecentlyViewed/RecentlyViewedTable.tsx
private-templates-service/client/src/components/Dashboard/RecentlyViewed/styled.tsx
private-templates-service/client/src/components/SideBar/SideBar.tsx
private-templates-service/client/src/store/templateOwner/actions.ts
private-templates-service/client/src/store/templateOwner/reducers.ts
private-templates-service/client/src/store/templateOwner/types.ts

This PR addresses these issues: 
[AB#34256](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34256) **"deprecated" text is located too right:**
[AB#34345](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34345): **Recently viewed elements on click:**
[AB#34331](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34331) **Profile pictures and names should display on first load:**
[AB#34326](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34326) **Profile picture and name for recently viewed column doesn't load properly:**
**Snapshot of new dashboard:**
**Videos:**
- Dashboard on refresh: https://microsoft-my.sharepoint.com/:v:/p/t-damott/Ee3jZ4oOPPJHi1By4xKa8ewBp0Y2Soecub9JnRbcO-fiRg?e=F1IWCV
- …

Fix Dashboard Bugs

---

private-templates-service/client/src/assets/strings.ts
private-templates-service/client/src/components/Common/SkipLink/SkipLink.tsx
private-templates-service/client/src/components/Common/SkipLink/index.ts
private-templates-service/client/src/components/Common/SkipLink/styled.tsx
private-templates-service/client/src/components/Dashboard/Dashboard.tsx
private-templates-service/client/src/components/Dashboard/index.ts
private-templates-service/client/src/components/NavBar/NavBar.test.tsx
private-templates-service/client/src/components/SideBar/SideBar.tsx
private-templates-service/client/src/globalStyles.tsx
private-templates-service/client/src/store/rootReducer.ts
private-templates-service/client/src/store/skiplink/actions.ts
private-templates-service/client/src/store/skiplink/reducer.ts
private-templates-service/client/src/store/skiplink/types.ts

This pr addresses [BUG34224](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34224) to create a skip to main content link to address accessibility.
The link won't be visible unless it receives a focus and it will get the focus if the user clicks **tab** while focusing on the **Dashboard** link on the SideBar. The link will change the user focus to RecentlyEdited.

Add skip link to main content

---

private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/styled.tsx
private-templates-service/client/src/components/Dashboard/RecentlyViewed/styled.tsx

Removed shadows from `Card` panel in template view page ([AB#34370](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34370)). Since `RecentlyViewed` component on Dashboard reuses the `Card` panel from template view page, shadows on from Dashboard are also gone ([AB#34169](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34169)).
#Screenshots

Removed shadows from Template View Page and Dashboard

---

private-templates-service/client/src/components/SideBar/SideBar.tsx
private-templates-service/client/src/components/SideBar/styled.tsx

[AB#34254](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34254) 
Overview of this change:
- Added functionality that allowed the user to click the logo to return to the homepage.
Snapshots: 
Before:
After:

 making the logo clickable ( sends user back to dashboard )

---

private-templates-service/client/src/components/Common/VersionModal/VersionModal.tsx
private-templates-service/client/src/components/Common/VersionModal/styled.tsx
private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/VersionCard/VersionCard.tsx
private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/VersionCard/styled.tsx
private-templates-service/client/src/utils/Scroller.tsx

Ticket: [TICKET-34327](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_sprints/taskboard/Adaptive%20Cards/Intern%20GitHub/Y20-VW/11?workitem=34327)
This PR makes the version lists scrollable when there are many template versions. 
It also contains a verticalScroll function for a custom Scroller class, [Seva's all templates branch](https://github.com/microsoft/adaptivecards-templates/blob/users/vsevolod/all-templates-page/private-templates-service/client/src/utils/AllCardsUtil/AllCardsUtil.ts) will also have a similar class with horizontalScroll. These changes will be combined to single Scroller class in a future PR/when the later branch is merged to dev.

Make version modal scrollable

---

private-templates-service/client/src/assets/strings.ts
private-templates-service/client/src/components/Dashboard/Dashboard.tsx
private-templates-service/client/src/components/Dashboard/RecentlyViewed/RecentlyViewed.tsx
private-templates-service/client/src/components/SideBar/SideBar.tsx

[AB#34088](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34088)
Changed references to the keyword "Template" to "Card" on the Dashboard. Changed a couple other labels on Dashboard as well to be aligned with the designs.
Migrated strings to the `strings.ts` file.

Changed references to "Template" to "Card"

---

private-templates-service/client/src/components/Common/ShareModal/ShareModal.tsx
private-templates-service/client/src/utils/TemplateUtil/TemplateUtil.ts

[AB#34088](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34088)
Removing the extra slash in shareable URL when displaying URL on dev or stage.
Did this by extracting the url builder function to the `TemplateUtil.tsx` file as I anticipate using it in other places. Modified this function so that it parses the URL and replaces `"//"` with `"/"`.
***I will only know if this worked if we push this to dev, but I'm fairly confident.***

Remove extra slash in Shareable URL on Dev/Stage

---

private-templates-service/azuredeploy.json

Ticket: [TASK-34415](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_sprints/taskboard/Adaptive%20Cards/Intern%20GitHub/Y20-VW/13?workitem=34415)
This PR enables the deploy to azure button to create a cosmosdb instance and database for the portal to connect to. 
Testing instructions can be found [here](https://github.com/microsoft/adaptivecards-templates/pull/211).

Add CosmosDB to deploy to azure button

---

private-templates-service/client/src/components/Common/TemplatesPage/TemplatesPage.tsx
private-templates-service/client/src/components/Common/TemplatesPage/TemplatesView/TemplatesView.tsx

[AB#34372](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34372)
Added tooltips on All Cards page and removed some console warnings.

Tooltips on All Cards page

---

private-templates-service/client/src/components/Shared/styled.tsx

[AB#34601](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34601)
Added one line to make tall adaptive cards scrollable on the Shared page.

Make Tall cards scrollable on shared view page

---

private-templates-service/client/src/components/SideBar/SideBar.tsx

This PR addresses [BUG34659](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34659) to fix display of SideBar while user is still logging in.

Fix SideBar display while user is logging in

---

private-templates-service/client/src/components/Common/Tags/styled.tsx
private-templates-service/client/src/components/Common/TemplatesPage/TagList/styled.tsx
private-templates-service/client/src/components/Dashboard/Dashboard.tsx
private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/VersionCard/styled.tsx
private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/styled.tsx
private-templates-service/client/src/components/Dashboard/styled.tsx
private-templates-service/client/src/components/NavBar/styled.tsx

Tickets: [TASK-34465](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34465), [BUG-34620](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34620)
Favorite tags that overflow now cut off and show ellipses. 
This PR also updates divs to h1 or h2 tags based on accessibility review.

Fix favorite tag overflow and add h1&h2 headers 

---

private-templates-service/client/package.json
private-templates-service/server/package.json

This PR temporarily removes the npm package dependencies from client and server as they are removed from the registry and cannot be republished until tomorrow (in preparation for publishing on adaptive cards npm account) so that we can continue to test new PRs on the dev site .

Temporarily remove npm packages

---

private-templates-service/README.md
private-templates-service/azuredeploy.json

Ticket: [TASK-34662](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_sprints/taskboard/Adaptive%20Cards/Intern%20GitHub/Y20-VW/14?workitem=34662)
This PR addresses the following concerns raised in [ISSUE-261](https://github.com/microsoft/adaptivecards-templates/issues/261):
- more detailed variable names
- updated documentation for common errors encountered
- unique cosmosdb name is now required as a parameter
**Testing this PR:** 
The deploy to azure button can be used to deploy the resources using the form, but the actual project will not build properly because the npm packages have been removed so that they can be switched to the official adaptivecards npm account: [PR-268](https://github.com/microsoft/adaptivecards-templates/pull/268)

Update ARM template & documentation
