microsoft/adaptivecards-templates

- azure-pipelines.yml
note that these resources have not been created yet. However it will not trigger any real deployments, should just fail
> change resources to stage

- private-templates-service/src/app.ts
really quick change. The path was updated as a part of graces refactor, but was not updated in this line of code causing the frontend to not render. this will fix that.
> Update path to build file

- private-templates-service/client/src/App.test.tsx
There was an undetected failure for the front end Jest test upon introduction of redux to dev. This is a quick fix for that. Issue will be raised to DevOps Champion to further investigate.
> quick fix for front end test fail due to introduction of redux

- .github/workflows/azure-dev.yml
- .github/workflows/azure-stage.yml
- private-templates-service/client/.env.dev
- private-templates-service/client/.env.staging
- private-templates-service/client/package.json
- private-templates-service/client/src/Config.tsx
These help us with what redirect the auth flow uses. I followed the following document to set this up:
https://medium.com/@tacomanator/environments-with-create-react-app-7b645312c09d
`process.env.NODE_ENV` is implicitly provided by react. 
`process.env.REACT_APP_HOST_ENV` is set by the `.env` files when deploying to our dev or stage environment.
> Environment Variables

- private-templates-service/client/src/App.tsx
- private-templates-service/client/src/components/Designer/Designer.tsx
- private-templates-service/client/src/components/SideBar/SideBar.tsx
Previously, every url change would result in a page refresh / network request. Our single page react app should not have this behavior.
Modifying the UI Fabric Nav component's default action changes this behavior:
```
const onNavClick = (event: any, element: any) => {
event.preventDefault();
history.push(element.url);
}
```
There was additional work to the designer because it previously appended the component to the root, overlaying the other components after navigating away. Now it will render like the other pages.
> Navigation Optimization

- private-templates-service/adaptivecards-templating-service/src/models/models.ts
- private-templates-service/adaptivecards-templating-service/src/storageproviders/InMemoryDBProvider.ts
Removed additional "name?" parameter
> removed additional name key

- src/GetTemplate/index.ts
Added Access-Control-Allow-Origin to allow using templates from JS sources properly
> Update Get template header

- private-templates-service/client/src/components/Common/AdaptiveCard/AdaptiveCard.tsx
> Try / Catch block to handle parsing error

- private-templates-service/adaptivecards-templating-service/src/models/mongo/TemplateModel.ts
- private-templates-service/adaptivecards-templating-service/src/models/mongo/UserModel.ts
Small fix to allow POST to MongoDB storage provider.
> Fix backend MongoDB errors

- private-templates-service/adaptivecards-templating-service/src/TemplateServiceClient.ts
- private-templates-service/adaptivecards-templating-service/src/tests/router.test.ts
- private-templates-service/adaptivecards-templating-service/src/util/templateutils.ts
**Changes:** 
- Update backend tests to pass valid JSON as templates
- Update backend to reject strings passed as templates or invalid JSON
> Fix backend tests

- private-templates-service/client/src/components/AdaptiveCardPanel/AdaptiveCardPanel.tsx
- private-templates-service/client/src/components/Common/AdaptiveCard/AdaptiveCard.tsx
- private-templates-service/client/src/components/Common/PublishModal/PublishModal.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/PreviewModal.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/TemplateInfo.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/styled.tsx
PR: [TASK-33719](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/33719), [TASK-33722](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/33722)
**Changes**
- Add dropdown for versions in template preview modal
- On version click, corresponding version card is rendered
**Screenshot**
> Template version dropdown UI

- private-templates-service/adaptivecards-templating-client/swagger.yaml
- private-templates-service/client/package-lock.json
- private-templates-service/client/package.json
- private-templates-service/client/src/components/Common/AdaptiveCard/AdaptiveCard.tsx
**Task 33790: Bind data to template JSON**
This PR enables Adaptive Card Templating. It also changes the type of data items to object in the swagger.yaml file. 
_To test_:
Run the client locally.
> Add Adaptive Card Templating

- private-templates-service/client/src/components/Common/AdaptiveCard/AdaptiveCard.tsx
- private-templates-service/client/src/components/Common/PublishModal/PublishModal.tsx
- private-templates-service/client/src/components/Common/Tags/Tags.tsx
- private-templates-service/client/src/components/Common/Tags/styled.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/PreviewModal.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/TemplateInfo.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/styled.tsx
- private-templates-service/client/src/components/SideBar/UserAvatar.tsx
- private-templates-service/client/src/store/currentTemplate/actions.ts
This allows you to save and delete tags from the template preview page.
The UI was already complete, this just hooks up button presses with redux actions which hit the backend api.
> Save and delete tags

- .github/workflows/dev-pr.yml
- .github/workflows/stage-pr.yml
- private-templates-service/adaptivecards-templating-service/src/tests/router.test.ts
** Task 33845: Run tests on PR **
Run tests whenever PRs are created and fix failing unit tests.
> Run tests on PR

- .github/workflows/azure-dev.yml
- private-templates-service/client/src/components/NavBar/NavBar.test.tsx
quick fix for the failing navbar test
solution: just need to mock useHistory().push() using jest
> navbar test fix

- .github/workflows/dev-pr.yml
- .github/workflows/stage-pr.yml
- private-templates-service/server/package.json
Overview of this PR:
- Added script for faster npm linking
- Fixed pipeline since it was failing on npm link
> testing pipeline and creating script

- private-templates-service/client/src/App.tsx
- private-templates-service/client/src/components/Dashboard/Dashboard.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/PreviewModal.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/TemplateInfo.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/styled.tsx
- private-templates-service/client/src/components/Dashboard/SearchPage/SearchPage.tsx
[AB#33859](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/33859)
As requested by Matt, template preview pages should be "bookmark-able". To do this, the preview page was changed from a modal to a normal page. 
No ui elements are changed.
> Opening a template now changes the url

- .github/workflows/azure-dev.yml
- private-templates-service/adaptivecards-templating-service/src/authproviders/AzureADProvider.ts
- private-templates-service/adaptivecards-templating-service/src/authproviders/Config.ts
- private-templates-service/adaptivecards-templating-service/src/tests/router.test.ts
This PR fixes the backend tests that failed due to the change in appID depending on which pipeline is being run (dev, staging, local).
> Fix backend tests 

- private-templates-service/client/src/store/recentTemplates/actions.ts
Removed hardcoded api key from recent templates action in redux store.
> Remove hardcoded api key

- private-templates-service/server/package-lock.json
- private-templates-service/server/package.json
- private-templates-service/server/src/app.ts
[TASK-33930](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_sprints/taskboard/Adaptive%20Cards/Intern%20GitHub/Y20-VW/09?workitem=33930)
This PR changes server to require secure cookies and configures site cookies for HttpOnly for compliance requirements. It also enables strict HSTS headers to pass SSLScanner tests.
**Main file to review:** `server/src/app.ts`
> Configure cookies for HttpOnly and secure cookies

- private-templates-service/client/src/components/Common/PublishModal/PublishModal.tsx
- private-templates-service/client/src/components/Common/ShareModal/ShareModalForm/ShareModalForm.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/TemplateInfo.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/styled.tsx
- private-templates-service/client/src/components/Designer/Designer.tsx
- private-templates-service/client/src/components/SideBar/SideBar.tsx
As per Stephane's request, features in progress will have pink buttons. These will be changed back to their original colors as features are completed. 
[AB#34143](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34143)
> change items in progress to pink

- private-templates-service/adaptivecards-templating-service/package-lock.json
- private-templates-service/adaptivecards-templating-service/package.json
- private-templates-service/adaptivecards-templating-service/src/TemplateServiceClient.ts
- private-templates-service/adaptivecards-templating-service/src/util/logger.ts
This PR addressed part of the [ACB33922](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/33922) compliance ticket related to logging. Now we'll log every time personal user data (oid) is accessed.
> Log when user data is accessed

- private-templates-service/adaptivecards-templating-client/swagger.yaml
- private-templates-service/adaptivecards-templating-client/typescript/api.ts
This PR updates the client SDK with changes from this [PR-147](https://github.com/microsoft/adaptivecards-templates/pull/147), which adds the last edited user to each template version.
> Add last edited user to client SDK

- private-templates-service/client/src/components/Dashboard/styled.tsx
[AB#34162](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34162)
just a quick styling fix for the footer
> fixed styling for footer

- private-templates-service/adaptivecards-templating-service/src/authproviders/AzureADProvider.ts
- private-templates-service/client/src/store/currentTemplate/actions.ts
- private-templates-service/client/src/store/recentTemplates/actions.ts
- private-templates-service/client/src/store/search/actions.ts
- private-templates-service/client/src/store/templates/actions.ts
- private-templates-service/client/src/utils/TemplateUtil/TemplateUtil.ts
- private-templates-service/client/src/utils/TemplateUtil/index.ts
Reverts microsoft/adaptivecards-templates#164 for demo until app registrations are fixed
> Revert "Check token expiration date in backend"

- private-templates-service/client/src/components/Common/Tags/Tags.tsx
- private-templates-service/client/src/components/Designer/SaveModal/SaveModal.tsx
- private-templates-service/client/src/components/Designer/SaveModal/styled.tsx
Simple sets max length of a tag
[AB#34078](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34078)
> Tags overflow

- private-templates-service/adaptivecards-templating-service/package-lock.json
- private-templates-service/server/package-lock.json
- private-templates-service/server/package.json
Forgot the package-lock.json when I added the adaptivecards-templating module!
> Add package-lock

- private-templates-service/client/src/components/Dashboard/RecentlyViewed/RecentlyViewedTable.tsx
- private-templates-service/client/src/components/Dashboard/RecentlyViewed/styled.tsx
Just needed to add one line of CSS to make spacing uniform on Dashboard.
Also fixed a console warning I introduced in my last PR (oops)
> Add margin-top to recently viewed component on Dashboard

- private-templates-service/client/src/components/Common/PublishModal/styled.tsx
- private-templates-service/client/src/components/Common/ShareModal/styled.tsx
- private-templates-service/client/src/components/Common/Tags/Tags.tsx
- private-templates-service/client/src/components/Common/Tags/styled.tsx
- private-templates-service/client/src/components/Common/VersionModal/styled.tsx
- private-templates-service/client/src/components/Dashboard/Footer/styled.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/VersionCard/styled.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/styled.tsx
- private-templates-service/client/src/components/Dashboard/SearchPage/styled.tsx
- private-templates-service/client/src/components/NavBar/styled.tsx
- private-templates-service/client/src/components/Shared/TemplateSourceInfo/styled.tsx
- private-templates-service/client/src/components/SideBar/SideBar.tsx
- private-templates-service/client/src/components/SideBar/styled.tsx
Addressed [TASK34235](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34235) accessibility issue with dynamic text resizing. Changed all the **px** units to **rem** units 1rem=16px on default browser settings.
> Change font-size in pixels to rem

- private-templates-service/adaptivecards-templating-service/src/TemplateServiceClient.ts
- private-templates-service/adaptivecards-templating-service/src/util/templateutils.ts
- private-templates-service/client/src/components/Common/VersionModal/VersionModal.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/VersionCard/VersionCard.tsx
- private-templates-service/client/src/components/Dashboard/RecentlyViewed/RecentlyViewedTable.tsx
- private-templates-service/client/src/utils/stringUtils.tsx
BUGS: [BUG-34251](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_sprints/taskboard/Adaptive%20Cards/Intern%20GitHub/Y20-VW/11?workitem=34251), [BUG-34322](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_sprints/taskboard/Adaptive%20Cards/Intern%20GitHub/Y20-VW/11?workitem=34322)
This PR fixes the incorrect template instance state in the recently viewed table and the publish/unpublish deleting template json bug.
> Fix version status bugs on dashboard & publish/unpublish json 

- private-templates-service/README.md
- private-templates-service/server/package.json
Our app is hard to start. I made a long ugly command that does the dirty work in one command. There is still some manual work replacing code.
> Startup commands and README update

- private-templates-service/client/package-lock.json
- private-templates-service/client/package.json
- private-templates-service/client/src/App.tsx
- private-templates-service/client/src/components/Designer/Designer.tsx
- private-templates-service/client/src/styled.tsx
The designer would previously overflow its width. These css changes fixes that. Why it did not work before I cannot tell you.
[AB#34101](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34101)
[AB#34161](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34161)
[AB#34049](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34049)
> Fix styling for designer

- private-templates-service/adaptivecards-templating-service/src/TemplateServiceClient.ts
- private-templates-service/adaptivecards-templating-service/src/tests/router.test.ts
Ticket: [BUG-34455](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_sprints/taskboard/Adaptive%20Cards/Intern%20GitHub/Y20-VW/12?workitem=34455)
Add all tags (no matter if template is published) to tags endpoint.
> Fix all tags bug

- private-templates-service/adaptivecards-templating-service/src/TemplateServiceClient.ts
Tickets: [BUG-34457](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34457), [BUG-34458](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34458), [BUG-34459](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34459)
This PR fixes bugs that cause hit counters to increase during template state changes or adding new tags.
> Fix hit counter bugs

- private-templates-service/client/src/components/AdaptiveCardPanel/styled.tsx
- private-templates-service/client/src/components/Common/PublishModal/styled.tsx
- private-templates-service/client/src/components/Common/ShareModal/ShareModal.tsx
- private-templates-service/client/src/components/Common/ShareModal/styled.tsx
- private-templates-service/client/src/components/Common/Tags/styled.tsx
- private-templates-service/client/src/components/Common/VersionModal/VersionModal.tsx
- private-templates-service/client/src/components/Common/VersionModal/styled.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/VersionCard/VersionCard.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/VersionCard/styled.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/styled.tsx
- private-templates-service/client/src/components/Dashboard/SearchPage/styled.tsx
- private-templates-service/client/src/components/Dashboard/TemplateList/styled.tsx
- private-templates-service/client/src/components/Dashboard/styled.tsx
- private-templates-service/client/src/components/Designer/Designer.tsx
- private-templates-service/client/src/components/Designer/SaveModal/styled.tsx
- private-templates-service/client/src/components/NavBar/styled.tsx
- private-templates-service/client/src/components/NoMatch/styled.tsx
- private-templates-service/client/src/components/Shared/TemplateSourceInfo/styled.tsx
- private-templates-service/client/src/components/SideBar/SideBar.tsx
- private-templates-service/client/src/components/SideBar/styled.tsx
- private-templates-service/client/src/globalStyles.tsx
[AB#34247](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_sprints/taskboard/Adaptive%20Cards/Intern%20GitHub/Y20-VW/12?workitem=34247)
This PR replaced `font-weight` selectors with the correct `font-family` value as per Naomi's designs. 
Note: 
Harsh is currently working on the Publish, Unpublish, and Share modals so I will contact him about changing those fonts!
> Change font 

- private-templates-service/client/src/store/auth/actions.ts
Refreshing a non-basepath page results in a blank page. 
This PR fixes that bug. See bug for steps to reproduce. [AB#34587](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34587)
Its really a one liner, my linter deleted some whitespace.
> Refresh page bug

- private-templates-service/client/src/components/Common/Tags/Tags.tsx
[AB#34520](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34520)
This PR trims the whitespace from the beginning and end of tags. 
NOTE: In working on this PR, Seva and I noticed this bug: [App crashes when a duplicate tag is added when running locally](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34605)
> Trim whitespace on tags

- pipelines/azure-dev.yml
- pipelines/dev-pr.yml
- pipelines/stage-pr.yml
Reverts microsoft/adaptivecards-templates#256
> Revert "Add PoliCheck"

- private-templates-service/azuredeploy.json
Ticket: [TASK-34563](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_sprints/taskboard/Adaptive%20Cards/Intern%20GitHub/Y20-VW/13?workitem=34563)
This PR updates the site location for the deploy to azure button to a dropdown menu. This PR also updates the ARM template to use a image from Dockerhub. This will be updated to use a image from a Microsoft public repository once no more dev changes are made to this repository.
> Update ARM template (location dropdown, dockerhub)

- private-templates-service/client/src/components/Dashboard/PreviewModal/PreviewModal.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/TemplateInfo.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/VersionCard/VersionCard.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/VersionCard/styled.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/styled.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/styled.tsx
This PR addresses [34654](https://microsoftgarage.visualstudio.com/Intern%20GitHub/_workitems/edit/34654) to fix main window in template preview becoming scrollable due to too many versions displayed in the Recent Releases.
I've also fixed the scrolling with touchpad issue and made shadow of NavBar visible.
Before:
After:
> Fix scroll on preview

- private-templates-service/client/src/components/Designer/styled.tsx
- private-templates-service/client/src/components/Shared/styled.tsx
[AB#34528](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34528)
This will help with ensuring there's no scrolling on the designer page.
> Set overflow-behaviour for Designer Page

- private-templates-service/client/src/components/Common/Tags/Tags.tsx
- private-templates-service/client/src/components/Common/Tags/styled.tsx
- private-templates-service/client/src/components/Common/TemplatesPage/TemplatesPage.tsx
- private-templates-service/client/src/components/Common/VersionModal/VersionModal.tsx
- private-templates-service/client/src/components/Dashboard/PreviewModal/TemplateInfo/TemplateInfo.tsx
- private-templates-service/client/src/components/Dashboard/TemplateList/TemplateListContent.tsx
- private-templates-service/client/src/components/NavBar/SearchBar/SearchBar.tsx
- private-templates-service/client/src/store/templateOwner/actions.ts
remake of previous pr due to too many conflicts
list of bug fixes:
hover on check or x results in a square
console warnings
adding a duplicate tag results in app crashing
[AB#34605](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34605)
> tags and warns

- templates/graph.microsoft.com/Files.json
- templates/graph.microsoft.com/Groups.json
- templates/graph.microsoft.com/Messages.json
- templates/graph.microsoft.com/Profile.data.json
- templates/graph.microsoft.com/Profile.json
- templates/graph.microsoft.com/Site.json
- templates/graph.microsoft.com/Users.json
We're updating the Graph templates to the latest version of Adaptive Cards Templating. 
We made smaller changes, but in general these are the changes we're bringing. This will allow [Graph Explorer](https://aka.ms/ge) to recover from the current failing situations.
> Updating Graph templates to latest version of templating
